PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT
  ?item
  ?itemLabel
  ?prop
  ?value
  (SAMPLE(?flag) AS ?flagg)
  (SAMPLE(?logo) AS ?logoo)
WHERE {
  VALUES ?prop { wdt:P13786 wdt:P1282 }

  ?item ?prop ?value .

  # P18 isn't suitable for an icon, so it isn't included
  OPTIONAL { ?item wdt:P41  ?flag }
  OPTIONAL { ?item wdt:P154 ?logo }


  OPTIONAL {
    ?item rdfs:label ?itemLabel .
    FILTER(LANG(?itemLabel) = "en")
  }
}
GROUP BY ?item ?itemLabel ?prop ?value
ORDER BY ?value ?item
