name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: "9 9 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze
      - run: dart run main.dart

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
